# https://medium.com/@nicola.vitaly/setting-up-high-availability-postgresql-cluster-using-patroni-pgbouncer-docker-consul-and-95c70445b1b1
# https://cloudraya.com/knowledge-base/set-up-high-availability-postgresql-cluster-using-patroni-on-cloud-raya/

# Start with a postgres image
FROM postgres:12

# Install basic packages
RUN apt-get update && apt-get upgrade -y
RUN apt-get install python3 python3-pip -y
RUN apt-get install libpq-dev -y

# Install pip packages
RUN pip install --upgrade pip setuptools --break-system-packages
RUN pip install psycopg2 patroni python-etcd --break-system-packages

# Copy config file
COPY ./patroni.yml /patroni.yml

# Add executables to PATH
RUN ln -s /usr/lib/postgresql/12/bin/* /usr/sbin

# Switch to postgres user
USER postgres

# Start patroni
ENTRYPOINT ["patroni", "patroni.yml"]